cache:
  paths:
    - node_modules/

before_script:
  - whoami
  - groups
  - pwd

stages:
  - deploy

develop-deploy:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - cp /home/secret/.env .env
    - rm -rf /home/projects/app | echo 'no folder'
    - mkdir /home/projects/app
    - cp . /home/projects/app -R
    - cd /home/projects/app
    - pm2 restart node ./bin/www
  after_script:
    - pm2 ps